rescan:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: parcelmon
    days:
      required: false
      default: 30
      example: 30
      selector:
        number:
          min: 0
          max: 3650
          step: 1
          unit_of_measurement: days
          mode: box
    limit:
      required: false
      default: 200
      example: 200
      selector:
        number:
          min: 1
          max: 2000
          step: 1
          mode: box

add_parcel:
  fields:
    tracking_number:
      required: true
      example: 36YPJ5053229
      selector:
        text:
    carrier:
      required: false
      default: auspost
      selector:
        select:
          options:
            - label: Australia Post
              value: auspost
            - label: Team Global Express
              value: tge
    status:
      required: false
      default: unknown
      selector:
        select:
          translation_key: parcel_status
          options:
            - in_transit
            - out_for_delivery
            - delivered
            - attempted
            - awaiting_collection
            - returned
            - unknown
    sender:
      required: false
      example: UCL Co. Ltd
      selector:
        text:
    eta:
      required: false
      example: Thursday 30 Jul
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: parcelmon

remove_parcel:
  fields:
    tracking_number:
      required: true
      example: 36YPJ5053229
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: parcelmon
